development:
  startup_wait: 15
  solr_host: localhost
  solr_port: 8080
  solr_home: /quod-dev/idx/h/hydra-solr
  solr_cntx: hydra-solr

testing:
  startup_wait: 9
  solr_home: /quod-dev/idx/h/hydra-solr
  solr_cntx: hydra-solr
